apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: decentraland
spec:
  selector:
    matchLabels:
      app: decentraland
  replicas: 1
  template:
    metadata:
      labels:
        app: decentraland
    spec:
      containers:
        - name: decentraland
          image: gcr.io/the-graph-staging/decentraland:latest
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: THEGRAPH_SENTRY_URL
              valueFrom:
                secretKeyRef:
                  name: thegraph-sentry-url
                  key: value
