apiVersion: v1
kind: Service
metadata:
  name: decentraland
spec:
  type: LoadBalancer
  selector:
    app: decentraland
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
